theme="material-design"
baseurl = "https://melakakini.github.io"
languageCode = "en-us"
title = "MELAKA KINI News"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "Your Disqus Name" # optional
copyright = "© 2017 Copyright Text"
[params]
description = "Your Site Description" # optional
twitter = "Your Twitter Name" # optional
gitlab = "Your Gitlab Name" # optional
github = "Your Github Name" # optional
facebook = "Your facebook Name" # optional
gplus = "Your Google+ profile name" # optional
linkedin = "Your LinkedIn Name" # optional
headerCover = "images/headerCover.png" # optional
footerCover = "images/footerCover.png" # optional
googleAnalyticsUserID = "Your Analytics User Id" # optional
[permalinks]
# post = "/:year/:month/:day/:title/" # optional